export {default as Homepage} from './Homepage/Homepage'
export {default as Write} from './Write/Write'
export {default as Single} from './Single/Single'
export {default as Settings} from './Settings/Settings'
export {default as Register} from './Register/Register'
export {default as Login} from './Login/Login'